package org.example.studyApp.common.values

object string {
    const val STUDY_PAL = "STUDY PAL"
    const val YOUR_POCKET_GUIDE_FOR_SCHOOL = "Your Pocket Guide for School"
    const val GET_STARTED = "Get Started"
    const val WHATS_NEW = "What's New"
    const val UPCOMING = "Upcoming"
    const val SEVEN = "7"
    const val EXAMS = "Exams"
    const val MENU = "MENU"
    const val HELP = "Help"
    const val LOGOUT = "Logout"
    const val TODAYS_SCHEDULE = "Today's Schedule"
    const val TUTORIALS = "Tutorials"
    const val PRACTICAL = "Practical"
    const val MATHS_101 = "Maths 101"
    const val CLASSES = "Classes"
    const val VOCABULARY = "Vocabulary"
    const val PENDING = "Pending"
    const val HOMEWORK = "Homework"
    const val NEW = "New"
    const val MESSAGE = "Message"
    const val EVERY_MONDAY = "Every Monday"
    const val EVERY_TUESDAY = "Every Tuesday"
    const val EVERY_WEDNESDAY = "Every Wednesday"
    const val EVERY_THURSDAY = "Every Thursday"
    const val THURSDAY = "Thursday"
    const val FRIDAY = "Friday"
    const val TIME_9 = "9:30 - 11:00"
    const val DESCRIPTION_MATHS = "Mathematics promotes logical thinking and mental rigor and is useful method for developing mental displine"
    const val DESCRIPTION_MATHS1 = "Additionally, comprehending mathematics is essential for learning other academic disciplines like physics, social studies and even music and art"
    const val LECTURER = "Lecturer"
    const val HAN = "Mr. Han"
    const val WORKSHOPS = "Workshops"
    const val LECTURES = "Lectures"
    const val SESSIONS = "Sessions"
    const val SCIENCE_101 = "Science 101"
    const val HISTORY_101 = "History 101"
    const val ART_101 = "Art 101"
    const val TIME_11 = "11:30 - 1:30"
    const val TIME_10 = "10:30 - 12:30"
    const val TIME_2 = "02:00 - 04:00"
    const val DIFFERENTIAL_EQUATION = "Differential Equation"
    const val MATRIX_ALGEBRA = "Matrix Algebra"
    const val MACROECONOMICS = "Macroeconomics"
    const val SHORTAGE_SCARCITY = "Shortage and Scarcity"
    const val COMMUNICATIONS = "Communications"
    const val STRATEGY = "Strategy"
    const val PRESENTATION_ROUND = "Presentation Round"
    const val SIGN_UP_FOR_ANOTHER_EXAM = "Sign up for another exam"
    const val MATHS_EXAM = "Maths Exam"
    const val TEACHERS = "Teachers"
    const val ROBERT = "Mr. Robert"
    const val ELIZABETH = "Mrs. Elizabeth"
    const val JAMES = "Mr. James"
    const val HAN_MESSAGE = "It's Friday"
    const val ROBERT_MESSAGE = "How about your Homework?"
    const val ELIZABETH_MESSAGE = "Good Job"
    const val JAMES_MESSAGE = "Can you help me with that?"






}