package org.example.MobileApp.common.values

object string {
    const val WELCOME = "Welcome to the app\n" + "& let’s get started"
    const val BEST_APP = "his app is the best app, thank you for downloading it. You won't regret using it."
    const val TERMS_AND_CONDITIONS = "By signing up, I agree to the Terms and Conditions and Privacy Policy."
    const val LOGIN = "Log in"
    const val ENTER_YOUR_DETAILS_TO_CONTINUE =  "Enter your details to continue"
    const val ENTER_YOUR_EMAIL = "Enter your e-mail"
    const val ENTER_YOUR_PASSWORD = "Enter your password"
    const val REMEMBER_ME = "Remember me"
    const val RECOVER_PASSWORD = "Recover password"
    const val GOOGLE = "Google"
    const val FACEBOOK = "Facebook"
    const val TWITTER = "Twitter"
    const val SIGN_UP = "Sign up"
    const val CREATE_AN_ACCOUNT = "Create an account"
    const val FULL_NAME = "Full name"
    const val USER_NAME = "Create a user name"
    const val CREATE_PASSWORD = "Create your password"
    const val CONFIRM_PASSWORD = "Confirm password"
    const val ENTER_YOUR_PHONE = "Enter your phone"
    const val NUMBER = "number"
    const val CONFIRMATION_CODE = "A confirmation code will be sent to your number to connect with the app"
    const val CONTINUE = "Continue"
    const val ENTER_THE_CODE_SENT = "Enter the 4 digit"
    const val SENT_TO = "code we sent"
    const val PLEASE_CHECK_MAIL = "Please check your mail. We've sent you "
    const val CONFIRMATION_LINK = "a confirmation link"
    const val PASSWORD_CONDITION = "Your password must be at least 8 characters long, " +
            "containing letters, digits and at least one special character"
    const val CONTAINS_LETTER = "Contains 1 letter"
    const val CONTAINS_DIGIT = "Contains 1 digit"
    const val CONTAINS_SPECIALCHARACTER = "Contains 1 special character"
    const val CREATE_A_PASSWORD = "Create a password"
    const val ENTER_PASSWORD = "Enter your password"
    const val TERMS_AND_CONDITION = "Terms & Conditions"
    const val TERMS = "These terms and conditions outline the rules and regulations for the use of company's website."
    const val CONDITIONS = "By accessing this website we assume you accept these terms and conditions. Do not continue to use website name if you do not agree to take all the terms and conditions stated on this page"
    const val AGREE_AND_CONTINUE= "Agree and Continue"
}